# counter-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
      - name: counter
        image: obtouf/base_repo:latest
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: "redis-service"
          name: LOG_FILE_PATH
          value: "/var/log/counter-app/counter.log"
        volumeMounts:
        - name: shared-logs
          mountPath: /var/log/counter-app
        #Sidecar container for logging
      - name: counter-logger
        image: busybox
        command: ["sh", "-c", "while true; do tail -f /var/log/counter-app/counter.log; sleep 5; done"]
        volumeMounts:
        - name: shared-logs
          mountPath: /var/log/counter-app
      # Shared volume for log files
      volumes:
      - name: shared-logs
        emptyDir: {}
      imagePullSecrets:
        - name: dockerhub-secret
