
services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: development
    depends_on:
      - redis
    networks:
      - massoud

  redis:
    image: "redis:alpine"
    networks:
      - massoud

networks:
  massoud:
    driver: bridge
