version: '3.8'

services:
  redis:
    image: redis:latest  # Use the official Redis image
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data  # Persist Redis data
    networks:
      - custom-network  # Attach to custom network

  web:
    build:  # Build your Flask app image
      context: ./app
      dockerfile: Dockerfile
    container_name: flask-app-container
    ports:
      - "5000:5000"
    depends_on:
      - redis  # Ensure Redis starts before the Flask app
    networks:
      - custom-network  # Attach to custom network

volumes:
  redis-data:  # Declare the volume for Redis data persistence

networks:
  custom-network:  # Define the custom network
